[default]
database.url = "sqlite:///./fast_api_template.db"
database.echo = false

jwt.secret_key = "your-secret-key-here"  # Change this in production!
jwt.algorithm = "HS256"
jwt.access_token_expire_minutes = 30
jwt.refresh_token_expire_days = 7

demo_user.password_hash = "$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewKyDAXxXxqQqG6"  # "password123"

[development]
server.reload = true
server.log_level = "debug"

[production]
server.reload = false
server.log_level = "info"
