"""Type stubs for dynaconf."""

from typing import Any, Dict

class Dynaconf:
    """Dynaconf configuration class."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def as_dict(self) -> Dict[str, Any]: ...
