from typing import Any, Dict, List, Optional, Union

class Dynaconf:
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...

class LazySettings(Dynaconf):
    def __init__(self, **kwargs: Any) -> None: ...
    jwt: Any
    access_token_expire_minutes: int
    refresh_token_expire_minutes: int

def Validator(*args: Any, **kwargs: Any) -> Any: ...
